### ISSUE TITLE
guidelines

### ISSUE THREAD

**Issue by flutter-painter** [grpcui/grpcui#31]
Hi,
Can this be used on any grpc server ?
I could run the example on mac and ran a grpc server locally on 0.0.0.0 port 8080 but get a HandshakeException

I also get error below when clicking on app.be-woow.com

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)), details: null, rawResponse: null, trailers: {})

**Comment by xclud** [comment]
Hi,

You must enable SSL/HTTPS for gRPC to work. Or if you are using a self signed certificate, you must add it to your client OS.

For the be-woow case, the server is down.
